[package]
name = "llm-game-sim"
version = "0.1.0"
authors = ["you"]

[models]
gpt-4o = { provider = "openai", model = "gpt-4o", max_tokens = 8192, temperature = 0.6 }
claude-3 = { provider = "anthropic", model = "claude-3", max_tokens = 8192, temperature = 0.5 }
imagen-3 = { provider = "google", model = "imagen-3" }
soundstorm = { provider = "google", model = "soundstorm" }

[dependencies]
